### ISSUE TITLE
Docker image on Docker Hub

### ISSUE THREAD

**Issue by a-nldisr** [prometheus-junkyard/mesos_exporter#16]
Dockerfile in this repo is pretty empty, can you update the dockerfile with the contents of #1

**Comment by juliusv** [comment]
Could you explain what exactly you would like to see in the current Dockerfile that is missing? The current one in this repo uses `sdurrheimer/alpine-golang-make-onbuild` as its base, which creates really small container images, so that's better than the one mentioned in #1 AFAICS (https://hub.docker.com/r/antonlindstrom/mesos-exporter/~/dockerfile/). Also, the `-config.file` option does not exist in the Mesos Exporter at head, so that is gone as well.

**Comment by a-nldisr** [comment]
Currently the Dockerfile content is this: 

---

FROM        sdurrheimer/alpine-golang-make-onbuild
MAINTAINER  The Prometheus Authors prometheus-developers@googlegroups.com

## EXPOSE      9105

I see no ADD of the code from mesos_exporter

**Comment by antonlindstrom** [comment]
@a-nldisr This does the adding of the code: https://github.com/sdurrheimer/alpine-golang-make-onbuild/blob/master/Dockerfile#L13

**Comment by a-nldisr** [comment]
Ok so in fact you only expose the port and call another image that has all the go code already inserted? Could it be an idea to configure the entrypoint for mesos_exporter in this dockerfile to take away confusion for an nitwit like me?
